name: Flutter My Build

on:
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-my-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "my-server1.3"
